export const IDEATION_TASK_REQUIRED = "IDEATION_TASK_REQUIRED" as const;
export const IDEATION_TASK_INPUT_CONFLICT = "IDEATION_TASK_INPUT_CONFLICT" as const;
export const IDEATION_REVIEW_ARTIFACT_TYPE_IMMUTABLE =
  "IDEATION_REVIEW_ARTIFACT_TYPE_IMMUTABLE" as const;
export const IDEATION_KICKOFF_NOT_ALLOWED = "IDEATION_KICKOFF_NOT_ALLOWED" as const;
export const IDEATION_KICKOFF_REQUIRES_RUNNING =
  "IDEATION_KICKOFF_REQUIRES_RUNNING" as const;
export const IDEATION_KICKOFF_NOT_ELIGIBLE = "IDEATION_KICKOFF_NOT_ELIGIBLE" as const;
export const IDEATION_KICKOFF_TASK_INVALID = "IDEATION_KICKOFF_TASK_INVALID" as const;
export const IDEATION_ALREADY_ACTIVE = "IDEATION_ALREADY_ACTIVE" as const;
export const IDEATION_KICKOFF_STATE_CONFLICT = "IDEATION_KICKOFF_STATE_CONFLICT" as const;
export const IDEATION_KICKOFF_PERSISTENCE_FAILED =
  "IDEATION_KICKOFF_PERSISTENCE_FAILED" as const;
export const IDEATION_PASS_BLOCKED = "IDEATION_PASS_BLOCKED" as const;
export const IDEATION_CONVERGED_BLOCKED = "IDEATION_CONVERGED_BLOCKED" as const;
export const IDEATION_METADATA_PARSE_WARNING =
  "IDEATION_METADATA_PARSE_WARNING" as const;
