import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname } from "node:path";

import {
  readTranscriptEnvelopes
} from "../../infrastructure/artifact/transcript/transcriptStore.js";
import type { ProtocolEnvelope } from "../../../types/protocol.js";
import { BubbleCommitError } from "./commitCommandRuntime.js";

function deriveDonePackageSummaryCandidate(content: string): string {
  const lines = content
    .split(/\r?\n/u)
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !line.startsWith("#"));

  return lines[0] ?? "Done package attached.";
}

export function deriveDonePackageSummary(content: string): string {
  const candidate = deriveDonePackageSummaryCandidate(content);
  const chars = Array.from(candidate);
  return chars.length > 240 ? `${chars.slice(0, 237).join("")}...` : candidate;
}

function formatCommitErrorMessage(input: {
  reasonCode: string;
  message: string;
  context: Record<string, unknown>;
}): string {
  return `${input.reasonCode}: ${input.message} context=${JSON.stringify(input.context)}`;
}

function extractPayloadSummary(envelope: ProtocolEnvelope): string | undefined {
  const payload = envelope.payload;
  if (
    typeof payload !== "object" ||
    payload === null ||
    Array.isArray(payload)
  ) {
    return undefined;
  }
  const summary = (payload as { summary?: unknown }).summary;
  if (typeof summary !== "string") {
    return undefined;
  }
  const trimmed = summary.trim();
  return trimmed.length > 0 ? trimmed : undefined;
}

function findLatestSummary(
  transcript: ProtocolEnvelope[],
  predicate: (envelope: ProtocolEnvelope) => boolean
): string | undefined {
  for (let index = transcript.length - 1; index >= 0; index -= 1) {
    const candidate = transcript[index];
    if (candidate === undefined || !predicate(candidate)) {
      continue;
    }
    const summary = extractPayloadSummary(candidate);
    if (summary !== undefined) {
      return summary;
    }
  }
  return undefined;
}

function renderAutoDonePackage(input: {
  bubbleId: string;
  round: number;
  generatedAt: string;
  convergenceSummary?: string;
  implementerSummary?: string;
  reviewerSummary?: string;
}): string {
  const convergenceSummary =
    input.convergenceSummary ?? "Convergence summary not available.";
  const implementerSummary =
    input.implementerSummary ?? "Implementer PASS summary not available.";
  const reviewerSummary =
    input.reviewerSummary ?? "Reviewer PASS summary not available.";

  return [
    "# Done Package",
    "",
    `Auto-generated by pairflow for bubble ${input.bubbleId} at ${input.generatedAt}.`,
    "",
    "## Bubble Context",
    `- Bubble ID: ${input.bubbleId}`,
    `- Round: ${input.round}`,
    "",
    "## Final Summary",
    convergenceSummary,
    "",
    "## Last Implementer PASS",
    implementerSummary,
    "",
    "## Last Reviewer PASS",
    reviewerSummary,
    "",
    "## Validation",
    "- [ ] Confirm tests/typecheck commands and outcomes",
    "- [ ] Confirm changed files are correct",
    "",
    "## Notes",
    "- Review and edit this document if you need a richer handoff package."
  ].join("\n");
}

export async function readOrCreateDonePackage(input: {
  donePackagePath: string;
  transcriptPath: string;
  bubbleId: string;
  round: number;
  nowIso: string;
  autoGenerate: boolean;
  implementer: string;
  reviewer: string;
}): Promise<string> {
  const existing = await readFile(input.donePackagePath, "utf8").catch(
    (error: NodeJS.ErrnoException) => {
      if (error.code === "ENOENT") {
        return undefined;
      }
      throw error;
    }
  );
  if (existing !== undefined && existing.trim().length > 0) {
    return existing;
  }

  if (!input.autoGenerate) {
    if (existing === undefined) {
      throw new BubbleCommitError(
        formatCommitErrorMessage({
          reasonCode: "COMMIT_DONE_PACKAGE_MISSING",
          message: `Missing done package artifact: ${input.donePackagePath}`,
          context: {
            bubble_id: input.bubbleId,
            command_name: "commit",
            done_package_path: input.donePackagePath,
            auto_generate: input.autoGenerate
          }
        })
      );
    }
    throw new BubbleCommitError(
      formatCommitErrorMessage({
        reasonCode: "COMMIT_DONE_PACKAGE_EMPTY",
        message: `Done package artifact is empty: ${input.donePackagePath}`,
        context: {
          bubble_id: input.bubbleId,
          command_name: "commit",
          done_package_path: input.donePackagePath,
          auto_generate: input.autoGenerate
        }
      })
    );
  }

  const transcript = await readTranscriptEnvelopes(input.transcriptPath, {
    allowMissing: true,
    toleratePartialFinalLine: true
  });
  const convergenceSummary = findLatestSummary(
    transcript,
    (entry) => entry.type === "CONVERGENCE"
  );
  const implementerSummary = findLatestSummary(
    transcript,
    (entry) => entry.type === "PASS" && entry.sender === input.implementer
  );
  const reviewerSummary = findLatestSummary(
    transcript,
    (entry) => entry.type === "PASS" && entry.sender === input.reviewer
  );

  const generated = renderAutoDonePackage({
    bubbleId: input.bubbleId,
    round: input.round,
    generatedAt: input.nowIso,
    ...(convergenceSummary !== undefined ? { convergenceSummary } : {}),
    ...(implementerSummary !== undefined ? { implementerSummary } : {}),
    ...(reviewerSummary !== undefined ? { reviewerSummary } : {})
  });
  await mkdir(dirname(input.donePackagePath), {
    recursive: true
  });
  await writeFile(input.donePackagePath, generated, "utf8");
  return generated;
}
